name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hycan:latest
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/hycan:cache
          cache-to: type=inline

      # Step 5: Notify Slack
      - name: Send Notification to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Build and Push Completed for branch: ${{ github.ref_name }}"}' ${{ secrets.SLACK_WEBHOOK_URL }}
