name: Update Wiki

on:
  push:
    branches:
      - main

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git User
      run: |
        git config --global user.name "rfc391"
        git config --global user.email "rfc391@users.noreply.github.com"

    - name: Debug Git Setup
      run: |
        echo "Checking working directory and files"
        ls -la
        echo "Checking docs folder contents"
        ls -la docs

    - name: Update Wiki
      run: |
        mkdir -p ./wiki
        cp -r docs/* ./wiki
        cd ./wiki
        git init
        git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/rfc391/HyCAN.wiki.git
        git add .
        git commit -m "Auto-update Wiki"
        git branch -M wiki
        git push origin wiki --force
